# Generated by Django 3.2.16 on 2024-08-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Любая картинка и желательно в тему поста', upload_to='blog_images', verbose_name='Изображение'),
        ),
    ]
